version: '3'

services:
  # ganachecli: simulated test rpc on dev environment
  # --account='0x740fc8d4ca7043fc17f8f5f98a113fcb157378936b688064b8fe80d4cf3e6d6e,10000000'
  ganache-cli:
    container_name: ganache-cli
    build:
      context: ./ganache
    ports:
      - 8545:8545

  # truffle-suite
  # volumes are used here to enable hot editing :) Nice trick!
  truffle-suite:
    container_name: truffle-suite
    build:
      context: truffledrizzle
    healthcheck:
      test: curl -sf -X POST --data '{"jsonrpc":"2.0","method":"eth_blockNumber","params":[],"id":1}' localhost:8545
      interval: 5s
      timeout: 5s
      retries: 5
    command: >
      sh -c "truffle compile &&
             truffle test &&
             truffle migrate &&
             cp -R output/contracts client/src/contracts/ &&
             cd client &&
             npm start"
    ports:
      - 3000:3000
    tty: true
    volumes:
      - ./truffledrizzle/client/src:/client/src
